// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use bigdecimal::BigDecimal;

use chrono::serde::ts_seconds_option;
use diesel::associations::{Associations, Identifiable};
use diesel::prelude::Insertable;
use diesel::{Queryable, Selectable};
use serde::{Serialize, Deserialize};
use uuid::Uuid;
use chrono::DateTime;
use chrono::offset::Utc;


#[derive(Queryable, Debug, Identifiable, Selectable)]
#[diesel(table_name = crate::schema::categories)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Category {
    pub id: i64,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
    pub category_uuid: Uuid,
    pub catogery_name: String,
    pub imgurl: String,
    pub order: Option<i64>,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(table_name = crate::schema::permissions)]
pub struct Permission {
    pub id: i64,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
    pub permission1: String,
}

#[derive(Queryable, Debug, Identifiable, Selectable)]
#[diesel(table_name = crate::schema::product_attributes)]
pub struct ProductAttribute {
    pub id: i64,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
    pub product_attrb_uuid: Uuid,
    pub product_id: Option<i64>,
    pub image_one: Option<String>,
    pub img_two: Option<String>,
    pub img_three: Option<String>,
}



#[derive(Queryable, Debug, Identifiable, Selectable)]
#[diesel(table_name = crate::schema::products)]
pub struct Product {
    pub id: i64,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
    pub product_uuid: Uuid,
    pub product_name: String,
    pub category_id: Option<i64>,
    pub description: String,
    pub family: Option<String>,
    pub variant: String,
    pub discount: i64,
}


#[derive(Queryable, Debug, Identifiable, Selectable, Associations)]
#[diesel(table_name = crate::schema::role_entities)]
#[diesel(belongs_to(Role))]
pub struct RoleEntity {
    pub id: i64,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
    pub entity_id: Option<String>,
    pub entity_name: Option<String>,
    pub role_id: i64,
    pub logger_id: Uuid,
}

#[derive(Queryable, Debug, Identifiable, Selectable)]
#[diesel(table_name = crate::schema::roles)]
pub struct Role {
    pub id: i64,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
    pub name: String,
}

#[derive( Debug, Selectable, Queryable, Identifiable,Insertable)]
#[diesel(check_for_backend(diesel::pg::Pg))]
#[diesel(table_name = crate::schema::users)]
#[diesel(primary_key(id))]
#[derive( Serialize)]
pub struct User {
    pub id: i64,
    #[serde(with = "ts_seconds_option")]
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
    pub user_id: Uuid,
    pub name: String,
    pub first_name: String,
    pub last_name: String,
    pub email: String,
    pub password: String,
    pub phone_number: Option<String>,
    pub isemail_verfied: Option<bool>,
    pub is_phone_verfied: Option<bool>,
    pub is_blocked: Option<bool>,
    pub is_active: Option<bool>,
}



